#!/usr/bin/env bash
#
# owns
#
# Copyright (c) 2013 fauno <fauno@endefensadelsl.org>
#
# See AUTHORS for a list of contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General
# Public License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.


# Es un poco ridículo que se use gettext para informar que falta gettext no?
for i in openssl base64 gettext; do
  if which $i &>/dev/null; then
    printf "$(gettext "%s is missing on PATH")" $i
    exit 1
  fi
done

if test -z "$1" ; then
  printf "$(gettext "Generates an hmac secret\n\nUsage:\t%s \"shared_secret\" \"your_secret\"\n")" \
         ${0##*/}
  exit 0
fi

printf "$2" | openssl sha1 -hmac "$1" -binary | base64
